### PR TITLE
Upgrade SDK to support Apache Statefun v3.2.0

### PR DESCRIPTION
**Pull request by AndrejMitrovic**
Hello,

This changeset includes support for v3.2.0 of Apache Statefun.

I've had my team review this changeset and this got OK'ed internally.

@aljoscha If you have the time to review this (even just a quick glance) it would be really great to get your OK before this gets merged in.

If you'd prefer we squash these commits before merge, that's okay too.

-----

The list of changes:

- The v3.x of the Statefun API includes changes to the Protocol buffers payloads, but also includes changes in how Apache Flink Statefun (TaskManager) calls into the functions.
- For example, on the first call to a function its registered state might be missing. The way registration is done is through a response back to Flink, which allocates space for the states and sends back a response. This is explained in detail [here](https://issues.apache.org/jira/browse/FLINK-20265).
- https://issues.apache.org/jira/browse/FLINK-21171
- The main API is still protocol buffers. However the internal payloads (client-defined types) are no longer protocol buffers. Instead they are tagged values called `TypedValue` (itself a protobuf message type). This allows the client code to pick its own serialization frameworks, and even use different serialization formats for different structures. It's up to the client code to pick what they want. This is explained in detail [here](https://issues.apache.org/jira/browse/FLINK-21171).
- v3.x supports cross-language unification of primitive types. This means that for primitive types like `int`, `float`, `string`, etc, they are all serialized in the same way, making them cross-language compatible. Again see [here](https://issues.apache.org/jira/browse/FLINK-21171) for more details. More specifically, these types are serialized with Protocol buffers, see `serialization.rs` in this repo how this is done.
- Any user-defined types which are expected to be passed over the wire must implement two traits: `Serializable`, and `TypeName`. `Serializable` defines how the type should be serialized, whereas `TypeName` encodes the full name of the type, which could for example be `example.io.truweb/my-type`.
- Added support for TTL for state values. Function's state can be set to never expire, or to expire after a certain number of time. When set to `AfterInvoke`, expiration time begins to count after last read or write, when set to `AfterWrite`, expiration time begins to count after the initial create or the last write.
- Added support for cancellation of delayed invocations by associating delayed invocations with cancellation tokens.

Additional changes include:
- Refactored the library and moved everything into its own module. Previously a lot of the code lived in `lib.rs`. There's still some usages of private fields within the library, as a workaround I'm using `pub (crate)` -- but we should probably implement getters here.
- Now contains 3 examples, one is based on the [playground](https://github.com/apache/flink-statefun-playground/tree/main/java) example and uses their own docker image. While the existing kafka example in the SDK has been ported to work with the new SDK. I've also added a separate example demonstrating delayed invocation, cancellation of delayed invocation, and state expiry.

For an intro to v3 changes see these release notes:
- https://flink.apache.org/2021/04/15/stateful-functions-3.0.0-remote-functions-front-and-center/

Newer minor changes since v3 include:
- https://flink.apache.org/2021/08/31/stateful-functions-3.1.0-release-announcement/
- https://flink.apache.org/2022/01/31/stateful-functions-3.2.0-release-announcement/

### CODE REVIEW

**Comment by aljoscha** [comment]
Oh wow, this _is_ a big change! As I mentioned earlier, I'm not up to date on latest Statefun developments so I don't have the bandwidth to review this right now. By now, you are way better suited to that because you have experience _using_ the code!

What would be best for you in maintaining and using the project?

**Comment by AndrejMitrovic** [comment]
I think perhaps giving me merge rights would be the best option.

My company is not prepared to take full ownership of the project, but I could find the time to occasionally review & merge PRs.

We'll likely submit patches ourselves from time to time when we find any issues.

**Comment by AndrejMitrovic** [comment]
Fixed up clippy / fmt. I'll go ahead and merge this. Thanks for giving me write access @aljoscha, appreciated!

**Comment by AndrejMitrovic** [comment]
Hey @aljoscha,

Would you mind adding my handle as a maintainer of the cargo package? https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

This should allow me to publish the create on crates.io.

Cheers~

**Comment by aljoscha** [comment]
You got it! Should have gotten the invites by now.

**Comment by AndrejMitrovic** [comment]
Received the invite. Thanks again~

**Comment by aljoscha** [comment]
Nah, thank you! I already saw you pushed out a new alpha release, with nice release notes!

**Comment by AndrejMitrovic** [comment]
Yep, although I've messed up the release a little bit due to the examples referencing the wrong version. But I'll fix it up soon~

**Pull request merged**
